### ISSUE TITLE
wrong type in SceKernelEqueue

### ISSUE THREAD

**Issue by psxdev** [CTurt/PS4-SDK#13]
@kR105 typedef int SceKernelEqueue;  has wrong type

If you try to call sceKernelDeleteEqueue with that type you will get 0x80020009 error. 

SceKernelCreateEqueue call internally to syscall 362 (aka sys_kqueue) and then to syscall 557 (aka sys_namedobj_create) and then it will return in first call parameter from  sceKernelCreateEqueue output from sys_kqueue plus/OR output from sys_namedobj_create left shifted 32 bits so SceKernelEqueue should be int64_t

You can check it with following code:

```
    SceKernelEqueue myqueue;
    int ret=sceKernelCreateEqueue(&myqueue,name);
    if(ret!=0)
    {
        debugNetPrintf(DEBUG,"Error creating event queue 0x%08X\n", ret);
        return -1;
    }
    else
    {
        debugNetPrintf(DEBUG,"Created event queue 0x%08X\n",queue);
    }
    ret=sceKernelDeleteEqueue(myqueue);
    if(ret!=0)
    {
        debugNetPrintf(DEBUG,"error sceKernelDeleteEqueue return: 0x%08X\n", ret);
    }
    else
    {
        debugNetPrintf(DEBUG,"sceKernelDeleteEqueue return: 0x%08X\n", ret);

    }
```

**Comment by CTurt** [comment]
Thanks for the report. Fixed as of the following commit:

https://github.com/CTurt/PS4-SDK/commit/472729f7c21a61da8448cfb85cdb34bee5bb961b
