### ISSUE TITLE
file.h

### ISSUE THREAD

**Issue by codetwink** [CTurt/PS4-SDK#17]
You have a ton of errors inside file.h

For example:
# define O_CREAT 0x0100

This value is most certainly NOT correct. The correct value is 0x0200, I was pulling my hair out trying to figure out why I couldn't create a file, then checked the FreeBSD code and seen the value was 0x0200.

**Comment by CTurt** [comment]
You are absolutely right! Don't remember where the old value came from, but certainly not from the FreeBSD 9 headers, as they should have!

I will try to get around to updating with the correct values soon (http://fxr.watson.org/fxr/source/sys/fcntl.h?v=FREEBSD9#L87)!

Thanks.

**Comment by CTurt** [comment]
Resolved in commit: https://github.com/CTurt/PS4-SDK/commit/224a9e20a26b6fa0d1b391a0a9d1928bf8192926
