### ISSUE TITLE
Please pick a license

### ISSUE THREAD

**Issue by yarwelp** [CTurt/PS4-SDK#19]
Please pick a license for your repo. Choosing a license allows others to easily and confidently know what they can and can not do with the things you've released.

I suggest choosing the ISC license. Here is a copy of the ISC license: https://gist.githubusercontent.com/eriknstr/84c5c986607f3e4245991480a40e2c45/raw/d998764c0e914964a380b74b28332ea0c7ca28e7/LICENSE, replace YYYY with the current year (2017), "John Doe" with your own name and john.doe@example.com with your own e-mail address (keep the angle-brackets). Alternatively if you do not wish to include your e-mail you can just remove the placeholder e-mail and angle-brackets.

**Comment by CTurt** [comment]
You can use this source in your own projects (open or closed source), as long as you give credit and link back to the original page, https://github.com/CTurt/PS4-SDK/.

Best license would be BSD license, but I'm not that formal. Dealing with licenses is generally a waste of time.
