### ISSUE TITLE
New syscall (raw) Macro does not generate proper PIC

### ISSUE THREAD

**Issue by hitodama** [CTurt/PS4-SDK#6]
If I compile any code with the newest SDK version (vanilla state), the following relocation error is issued:

``` Bash
clang -c -o build/main.o source/main.c -I/tmp/git/t/PS4-SDK/libPS4/include -I. -Iinclude -O2 -fPIC -ffreestanding -fno-builtin -Wall -masm=intel -target x86_64-scei-ps4-elf -m64 -mcmodel=large
ld.gold build/*.o -o hello.elf -L/tmp/git/t/PS4-SDK/libPS4 -L. -Llib -shared -fPIE -lPS4
ld.gold: error: /tmp/git/t/PS4-SDK/libPS4/libPS4.a(kernel.o): requires dynamic R_X86_64_PC32 reloc against 'rawSyscall' which may overflow at runtime; recompile with -fPIC
ld.gold: error: /tmp/git/t/PS4-SDK/libPS4/libPS4.a(module.o): requires dynamic R_X86_64_PC32 reloc against 'rawSyscall' which may overflow at runtime; recompile with -fPIC
Makefile:26: recipe for target 'hello.elf' failed
make: *** [hello.elf] Error 1
```

For an indication on the error: https://tecnocode.co.uk/2014/10/01/dynamic-relocs-runtime-overflows-and-fpic/ (though not exactly the same issue I suppose).
Basically, the way you inject the syscall isn't playing nice with generating PIC :) I think there are multiple ways to "fix" this one way or another.

I will look at it tomorrow if you don't want to invest time. I am getting frustrated with the loader, so its a more pressing issue to me right now >:(

**Comment by CTurt** [comment]
Using MinGW it works fine. Not sure what clang is doing.

**Comment by hitodama** [comment]
Using ld I get the same:
ld: /tmp/git/t/PS4-SDK/libPS4/libPS4.a(kernel.o): relocation R_X86_64_PC32 against symbol `rawSyscall' can not be used when making a shared object; recompile with -fPIC

Compiling the SDK with gcc I also run into the issue.

It could be that mingw is simply to ignorant to detect any potential overflow and doesn't care.

**Comment by CTurt** [comment]
Fixed (albeit slightly messily) as of this commit:

https://github.com/CTurt/PS4-SDK/commit/92e42b3f47be982e04a654183b374c7a2664957c
